cycjimmy/semantic-release-action

- README.md
- Fixes #10 
Just updated the `README.md` mentioning that plugins passed in `extra_plugins` must be specified in the semantic release [plugins](https://semantic-release.gitbook.io/semantic-release/usage/configuration#plugins
) array as well
> extra_plugins must be in release config

- .github/workflows/checkPullRequest.yml
- .github/workflows/testRelease.yml
- src/handleOptions.js
parameter `branch` does not work in semantic v16(#15)
#15
- Fixes #15 
fix parameter `branch` does not work in semantic v16
> fix(branch): parameter `branch` does not work in semantic v16

- .github/workflows/testRelease.yml
- README.md
- action.yml
- src/outputs.json
- src/windUpJob.task.js
Adds the [release notes](https://semantic-release.gitbook.io/semantic-release/developer-guide/js-api#nextrelease) of the next release to the output of the action.
Dry run semantic-release-action to determine nextRelease version and create a PR for new version.
```yml
- name: Dry run Semantic release
id: semantic
uses: cycjimmy/semantic-release-action@latest
with:
dry_run: true
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
- name: Create Pull Request
uses: peter-evans/create-pull-request@v2
if: steps.semantic.outputs.new_release_published == 'true'
with:
branch: 'release/${{ steps.semantic.outputs.new_release_version }}'
token: ${{ secrets.GITHUB_TOKEN }}
commit-message: 'chore(Version): Prepare v${{ steps.semantic.outputs.new_release_version }}. Merge …
```
> feat: add release notes to output

- README.md
Nothing
There is no hash in https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables
The current URL of the page seems https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
> docs: correct a link

- index.js
- Fixes #57 
Warnings during dependencies installation are not meant to make crash the release.
So by setting the loglevel to error we are sure we stop the release process only when a real error occurs.
> fix: use error loglevel for installing dependencies

- README.md
- action.yml
- src/index.js
- src/inputs.json
You can now select another working directory like a subdirectory of the project to run semantic release.
The goal is to manage a mono-repo with semantic release and run this action in every project.
> feat: add working dir

- .github/workflows/release.yml
- README.md
- action.yml
switch operating environment to node16
BREAKING CHANGE: switch operating environment to node16
#92, #96
`semantic-release@19` no longer supports environments below node16
> feat: switch operating environment to node16

- README.md
- src/handleOptions.js
In some cases, you may want to provide a version for the config you want to extend. This change will now pass the correct format for such a case down to semantic-release (just the module name, i.e. removing everything after `@`). It handles scoped packages with a negative lookbehind to make sure that package names starting with `@` are not replaced. The format passed to npm install is kept the same as before, so that will keep on working.
More specifically, such an input will now work:
```yaml
extends: |
@semantic-release/apm-config@^9.0.0
@mycompany/override-config
```
> feat: handle versioned extends inputs correctly

- src/windUpJob.task.js
Fixed that now the `last_release_version` output gets set even when no new release has been published
With this change, the `last_release_version` option will be set whenever available.
Previously this has been set only when a new release version was available, too.
> Fix set last_release_version output even if no release has been published

- .github/CONTRIBUTING.md
- .github/workflows/checkPullRequest.yml
- .github/workflows/testRelease.yml
- README.md
Refers to this repository's default branch as `main`, which is the new default for GitHub repositories, and is more politically correct. Note that you will still need to [rename the master branch manually](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch).
> chore: rename default branch to main

- README.md
- action.yml
- src/outputs.json
- src/windUpJob.task.js
- Fixes #135
This adds new outputs for the git head and tag for new and last release: new_release_git_head, new_release_git_tag, last_release_git_head, last_release_git_tag
> feat: Add new outputs for git head and tags

- README.md
- Fixes #148
This PR updates the [README section: Semantic version](https://github.com/cycjimmy/semantic-release-action/blob/main/README.md#semantic_version).
- Advice is updated about how to use the `semantic_version` parameter.
- Compatibility issues with [Version 20.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0) of [semantic-release](https://github.com/semantic-release/semantic-release/) are explained.
- Trailing whitespace in the README was also removed.
See https://github.com/MikeMcC399/semantic-release-action/blob/readme-semantic_version/README.md#semantic_version to conveniently preview the revised section.
> docs(README): update semantic_version description

- README.md
- action.yml
- src/handleOptions.js
- src/index.js
- src/inputs.json
-  I did not find any related issues, nor did I create one (sorry). Creating a pull request directly was the fastest way for me to ask for this feature.
I recently tried to use this action to comment the next version number under pull request that merge back into main. However, `semantic-release` blocks the release generation when the job is executed on a pull request. The option `ci = false` can be used to disable the pull request detection.
I'm sure there are other use-cases and I think it would be good to expose the `ci` config for `semantic-release`. I checked the changelog, and apparently `ci` was added in [v16.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v16.0.0), initally as `noCi` and later renamed to `ci`. In the `handleOptions` I have added both options …
> feat: add `ci` input parameter

- src/preInstall.task.js
N/A
Disable npm `--silent` flag if debug mode is enabled. This allows to get more information about the error that happened during installation, instead of just "npm command failed".
Debug mode can be enabled when re-running a failed job and checking the "Enable debug logging" checkbox.
> fix(preInstall): disable silent flag if debug mode is enabled

- src/windUpJob.task.js
- N/A
When no new release has been published, the outputs related to the last one are not set. This PR sets these outputs as soon as we have the needed information about the last release.
> fix(windUpJob): set last_release outputs before returning

- .github/workflows/release.yml
- README.md
- action.yml
- package-lock.json
- package.json
- src/handleOptions.js
- src/index.js
- src/windUpJob.task.js
- Fixes #168
Node20 is being rolled out on [github runnes](https://github.com/actions/runner/issues/2619#issuecomment-1679003443)
> feat: update node version to 20

- README.md
- Fixes #[Add issue number here.]
update readme to reference checkout@v4 rather then checkout@v3, as v4 is the latest as indicated here:  https://github.com/actions/checkout/releases
If it is prefeed to keep it as v3, then this pr can be closed.
> docs: update readme to ref checkout@v4

- README.md
- action.yml
- src/handleOptions.js
- src/index.js
- src/inputs.json
- Fixes #197 
- add `repository_url` input
- handle it at `index.js`
- update `RADME.md`
> feat: add repository_url input

- README.md
- action.yml
- src/handleOptions.js
- src/index.js
- src/inputs.json
- Fixes https://github.com/semantic-release/semantic-release/issues/3518, https://github.com/semantic-release/semantic-release/issues/1890
This PR adds the ability to unset the `GITHUB_ACTIONS` environment variable. In a number of scenarios it can be useful to validate a PR being merged to a branch will result in a valid release. However, due to the way the detection works in [env-ci](https://github.com/semantic-release/env-ci/blob/master/services/github.js) it will always pick up the branch from GitHub from environment variables that can't be overridden, even when setting `ci: false`. Removing the `GITHUB_ACTIONS` environment variable allows semantic release to pickup the branch from Git. This allows for a workflow to checkout the base branch of a PR, do a dummy merge of the PR and then …
> feat: add ability to unset GITHUB_ACTION env var

- package-lock.json
This resolves dependency version mismatch when using semantic-version 24.2.4
- Fixes #243 
The error was related with incompatible `markedjs` version between `semantic-release` and `marked-terminal`.
https://github.com/semantic-release/semantic-release/issues/3725#issuecomment-2892031828
> fix: update marked terminal to v7.3.0

- .github/workflows/release.yml
- action.yml
- Fixes #247
The action now uses node 24 so that users can release libraries that require node 22 or 24. See https://github.com/cycjimmy/semantic-release-action/issues/247 for details.
BREAKING CHANGE: this action now runs using node 24
> feat!: update node version on runner to 24
